version: '3.2'

services:
  elasticsearch:
    image: "elasticsearch"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./elasticsearch/config/elasticsearch-local.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - main
    environment:
      - node.name=elasticsearch
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - cluster.name=es-docker-cluster
      # - "ELASTIC_PASSWORD=whenguardian2021"
      - discovery.type=single-node
    restart: on-failure

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - main
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      dockerfile: Dockerfile.dev
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "5601:5601"
    volumes:
      - type: bind
        source: ./kibana/config/kibana-local.yml
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - main
    restart: on-failure
    depends_on:
      - elasticsearch

networks:
  main:
    driver: bridge

volumes:
  elasticsearch:
