version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - "ES_JAVA_OPTS=-Xmx6g -Xms1g"
      - cluster.name=es-docker-cluster
      - "ELASTIC_PASSWORD=whenguardian2021"
      - discovery.seed_hosts=elasticsearch2
    restart: on-failure
    networks:
      main:
          ipv4_address: 10.0.2.15
  elasticsearch2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: volume
        source: elasticsearch2
        target: /usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch2
      - "ES_JAVA_OPTS=-Xmx6g -Xms1g"
      - cluster.name=es-docker-cluster
      - "ELASTIC_PASSWORD=whenguardian2021"
      - discovery.seed_hosts=elasticsearch
    restart: on-failure
    networks:
      - main

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - main
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    networks:
      - main
    restart: on-failure
    networks:
      main:
          ipv4_address: 10.0.2.11
    depends_on:
      - elasticsearch

networks:
  main:
    external:
      name : main-overlay

volumes:
  elasticsearch:
