ARG ELK_VERSION

FROM node:14.16.0-alpine3.13 as node

ARG ELK_VERSION

RUN apk add git

WORKDIR /usr/app/

RUN git clone --single-branch --depth=1 --branch 7.11 https://github.com/elastic/kibana.git

RUN apk add gcc make python3 libc-dev g++

WORKDIR /usr/app/kibana

RUN yarn kbn bootstrap
